http:
  routers:
    pios_platform_api:
      rule: "Host(`app.political-os.com.br`, `political-os.com.br`, `www.political-os.com.br`) && PathPrefix(`/api`)"
      entryPoints:
        - websecure
      priority: 1000
      tls:
        certResolver: letsencryptresolver
      service: pios_api@file

    pios_platform_frontend:
      rule: "Host(`app.political-os.com.br`, `political-os.com.br`, `www.political-os.com.br`)"
      entryPoints:
        - websecure
      priority: 100
      tls:
        certResolver: letsencryptresolver
      service: pios_frontend@file
