http:
  services:
    pios_frontend:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://frontend:80"

    pios_api:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://api:3002"
